trigger:
- main

variables:
  BUILD_TYPE: Debug

jobs:
  - job: Windows
    pool:
      vmImage: 'windows-2022'
    steps:
      - script: |
          pip3 install ninja
        displayName: Install Tools
      - script: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cmake -D CMAKE_BUILD_TYPE=$(BUILD_TYPE) -G Ninja -B build -S .
          cmake --build build --config $(BUILD_TYPE)
        env:
            CC: cl
            CXX: cl
        displayName: Build

  - job: Linux
    pool:
      vmImage: 'ubuntu-22.04'
    steps:
      - script: |
          pip3 install ninja
        displayName: Install Tools
      - script: |
          cmake -D CMAKE_BUILD_TYPE=$(BUILD_TYPE) -G Ninja -B build -S .
          cmake --build build --config $(BUILD_TYPE)
        env:
            CC: clang-15
            CXX: clang++-15
        displayName: Build

  - job: MacOS
    pool:
      vmImage: 'macOS-12'
    steps:
      - script: |
          pip3 install ninja
        displayName: Install Tools
      - script: |
          cmake -D CMAKE_BUILD_TYPE=$(BUILD_TYPE) -G Ninja -B build -S .
          cmake --build build --config $(BUILD_TYPE)
        env:
            CC: clang
            CXX: clang++
        displayName: Build
